version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh 192.168.0.72:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
    networks:
      nginx:
      dockerbridge:
        ipv4_address: 192.168.0.79
  mongo:
    image: mongo
    restart: always
    ports:
      - 27021:27017
    volumes:
      - ./data:/data/db
    networks:
      nginx:
      dockerbridge:
        ipv4_address: 192.168.0.72
networks:
  nginx:
    external:
      name: nginx
  dockerbridge:
    external:
      name: dockerbridge
