version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27021 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - 27021:27017
    volumes:
      - ./data:/data/db
